import { ChildVuex } from 'super-vuex';
const child = new ChildVuex('demo');
export default child;
child.setState({
  value: 'Hello World',
  mode: 0,
  gmode: 0,
  animates: ["bounce", "flash", "pulse", "rubberBand", "shake", "swing", "tada", "wobble", "jello", "bounceIn", "bounceInDown", "bounceInLeft", "bounceInRight", "bounceInUp", "bounceOut", "bounceOutDown", "bounceOutLeft", "bounceOutRight", "bounceOutUp", "fadeIn", "fadeInDown", "fadeInDownBig", "fadeInLeft", "fadeInLeftBig", "fadeInRight", "fadeInRightBig", "fadeInUp", "fadeInUpBig", "fadeOut", "fadeOutDown", "fadeOutDownBig", "fadeOutLeft", "fadeOutLeftBig", "fadeOutRight", "fadeOutRightBig", "fadeOutUp", "fadeOutUpBig", "flip", "flipInX", "flipInY", "flipOutX", "flipOutY", "lightSpeedIn", "lightSpeedOut", "rotateIn", "rotateInDownLeft", "rotateInDownRight", "rotateInUpLeft", "rotateInUpRight", "rotateOut", "rotateOutDownLeft", "rotateOutDownRight", "rotateOutUpLeft", "rotateOutUpRight", "slideInUp", "slideInDown", "slideInLeft", "slideInRight", "slideOutUp", "slideOutDown", "slideOutLeft", "slideOutRight", "zoomIn", "zoomInDown", "zoomInLeft", "zoomInRight", "zoomInUp", "zoomOut", "zoomOutDown", "zoomOutLeft", "zoomOutRight", "zoomOutUp", "hinge", "jackInTheBox", "rollIn", "rollOut"],
  groups: ["callout.bounce", "callout.shake", "callout.flash", "callout.pulse", "callout.swing", "callout.tada", "transition.fadeIn", "transition.fadeOut", "transition.flipXIn", "transition.flipXOut", "transition.flipYIn", "transition.flipYOut", "transition.flipBounceXIn", "transition.flipBounceXOut", "transition.flipBounceYIn", "transition.flipBounceYOut", "transition.swoopIn", "transition.swoopOut", "transition.whirlIn", "transition.whirlOut", "transition.shrinkIn", "transition.shrinkOut", "transition.expandIn", "transition.expandOut", "transition.bounceIn", "transition.bounceOut", "transition.bounceUpIn", "transition.bounceUpOut", "transition.bounceDownIn", "transition.bounceDownOut", "transition.bounceLeftIn", "transition.bounceLeftOut", "transition.bounceRightIn", "transition.bounceRightOut", "transition.slideUpIn", "transition.slideUpOut", "transition.slideDownIn", "transition.slideDownOut", "transition.slideLeftIn", "transition.slideLeftOut", "transition.slideRightIn", "transition.slideRightOut", "transition.slideUpBigIn", "transition.slideUpBigOut", "transition.slideDownBigIn", "transition.slideDownBigOut", "transition.slideLeftBigIn", "transition.slideLeftBigOut", "transition.slideRightBigIn", "transition.slideRightBigOut", "transition.perspectiveUpIn", "transition.perspectiveUpOut", "transition.perspectiveDownIn", "transition.perspectiveDownOut", "transition.perspectiveLeftIn", "transition.perspectiveLeftOut", "transition.perspectiveRightIn", "transition.perspectiveRightOut"],
  list: [
    { msg: 'Thomas' },
    { msg: 'Dave Klingeberg' },
    { msg: 'Berni Leitzke' },
    { msg: 'Toni D\'Angelo' },
    { msg: 'Dimitri Reifschneider' },
    { msg: 'Sebastian Appelt' },
    { msg: 'Sergei Kulichkov' },
    { msg: 'Jakob Hirscheider' },
    { msg: 'Claus Gehrke' },
    { msg: 'Axel Klemm' },
    { msg: 'Thomas' },
    { msg: 'Berit Haak' },
    { msg: 'Bernd Feldmayer' },
    { msg: 'Selina Kuinn' },
    { msg: 'Walter Jenner' },
    { msg: 'Adnan Mujkanovic' },
    { msg: 'Lilia Kraft' },
    { msg: 'Aleksey Razbakov' },
    { msg: 'Dominik Arnoldi' },
    { msg: 'Peter Dickten' },
    { msg: 'Robert Hostlowsky' },
    { msg: 'Michael Westrich' },
    { msg: 'Karlheinz Kleinhenz' },
    { msg: 'kelyane' },
    { msg: 'Fabian Klose' },
    { msg: 'Valentin Schellhaas' },
    { msg: 'Simon Ittmann' },
    { msg: 'Karthikeyan Palaniswamy' },
    { msg: 'Miloš Sutanovac' },
    { msg: 'Joe Flo' },
    { msg: 'Philipp Renoth' },
    { msg: 'Daniel Schleindlsperger' },
    { msg: 'Markus Heer' },
    { msg: 'Örsan' },
    { msg: 'Thomas Zolynski' },
    { msg: 'Max Langer' },
    { msg: 'Martin Straub' },
    { msg: 'Alex Gretschann' },
    { msg: 'Andreas' },
    { msg: 'leif' },
    { msg: 'Dejan Dujmovic' },
    { msg: 'Alexander' },
    { msg: 'Mario Lemke' },
    { msg: 'Carlos Blas C' },
    { msg: 'Alexander Koenig' },
    { msg: 'Robert Kaiser' },
    { msg: 'Vladimir Kalenyuk' },
    { msg: 'Marcus S.' },
    { msg: 'Jonas Albrecht' },
    { msg: 'plusgut' },
    { msg: 'Anton Caceres' },
    { msg: 'Marc' },
    { msg: 'ray Qin' },
    { msg: 'Constantin Bahlmann' },
    { msg: 'Benedict B.' },
    { msg: 'Hyunjoo' },
    { msg: 'Basti' },
    { msg: 'Jiří Chára' },
    { msg: 'Orhan' },
    { msg: 'Valery Mikhnevich' },
    { msg: 'Flo' },
    { msg: 'Ines Akrap' },
    { msg: 'Ping Chen' },
    { msg: 'Carsten Rösnick-Neugebauer' },
    { msg: 'Le Tu Luong' },
    { msg: 'Habtom' },
    { msg: 'Florian Schinagl' },
    { msg: 'Lorincz Csaba' },
    { msg: 'David Lutkin' },
    { msg: 'Pu Bär' },
    { msg: 'Luisa Ruppert' },
    { msg: 'Thiemo Antonczyk' },
    { msg: 'Lanei L' },
    { msg: 'Xa Javier' },
    { msg: 'Philipp Neugebauer' },
    { msg: 'Adelina Gerdt' },
    { msg: 'Dominic Frei' },
    { msg: 'Matheus Lisboa de Barros' },
    { msg: 'Francesco' },
    { msg: 'Admir Mustafic' },
    { msg: 'Dominic' },
    { msg: 'Lasse' },
    { msg: 'Stefan Oblinger' },
    { msg: 'Sebastian Feldmann' },
    { msg: 'Kai S. Huxmann' },
    { msg: 'Sebastian Schwaiger' },
    { msg: 'Max Tafelmayer' },
    { msg: 'Oliver Wahl' },
    { msg: 'Sebastian Sellmeier' },
    { msg: 'B. R.' },
    { msg: 'Michael Haeuslmann' },
    { msg: 'Achim Rohn' },
    { msg: 'Tobias Stadler' },
    { msg: 'Ben Otto' },
    { msg: 'oli' },
    { msg: 'Vanessa Böhner' },
    { msg: 'David S.' },
    { msg: 'Kiki Sergel' },
    { msg: 'Stefan' },
    { msg: 'Elaine B.' }
  ],
  list1: [],
  list2: []
});